name: Stale Branches

on:
  schedule:
    - cron: '30 15 * * *'

permissions:
  issues: write
  contents: write

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Stale Branches
        uses: crs-k/stale-branches@v8.2.2
        with:
          days-before-stale: 2
          days-before-delete: 3
          ignore-issue-interaction: true
