name: Test Reproducibility
run-name: ${{ inputs.issue_branch }}

on:
  workflow_dispatch:
    inputs:
      issue_branch:
        description: 'Branch with the issue to reproduce'
        required: true
      issue_number:
        description: 'Number of the issue to reproduce'
        required: true

jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - name: Install repo2docker
        run: pip install jupyter-repo2docker
      - name: Checkout issue branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.issue_branch }}
      - name: Build image
        run: repo2docker --no-run --image-name=issue-env .
      - name: Execute notebook
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/work \
          issue-env \
          jupyter nbconvert --to notebook --execute /work/issue-${{ github.event.inputs.issue_number }}/issue-${{ github.event.inputs.issue_number }}.ipynb
